sudo: false
language: bash
os:
  - linux
env:
  matrix:
    - HARDWARE=esp8266com/esp8266 \
      CORE=https://github.com/esp8266/Arduino/archive/6d3f0b40239b61472a1a0777b402f00d1165beec.tar.gz \
      BOARD='--board esp8266com:esp8266:nodemcuv2  --pref custom_CpuFrequency=nodemcuv2_80 --pref custom_FlashSize=nodemcuv2_4M1M'
    - HARDWARE=espressif/esp32 \
      CORE=https://github.com/espressif/arduino-esp32/archive/3a4ec66d41615cbb1c3e830cb6e761cdc4cca9d3.tar.gz \
      BOARD='--board espressif:esp32:heltec_wifi_kit_32 --pref custom_FlashFreq=heltec_wifi_kit_32_80'

install:
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16
  - mkdir -p $HOME/arduino_ide; cd $HOME/arduino_ide
  - curl -L http://downloads.arduino.cc/arduino-1.8.5-linux64.tar.xz | tar xJ --strip 1
  - export PATH="$HOME/arduino_ide:$PATH"
  - cd $HOME/arduino_ide/hardware
  - mkdir -p $HARDWARE; cd $HARDWARE
  - curl -L $CORE | tar xz --strip 1
  - cd tools; python get.py

before_script:
  - mkdir -p $HOME/Arduino/libraries
  - cp -r $TRAVIS_BUILD_DIR $HOME/Arduino/libraries/WifiEspNow
  - export DISPLAY=:1.0
  - arduino $BOARD --save-prefs
  - arduino --get-pref

script:
  - |
     NFAIL=0
     for SKETCH in $(find $TRAVIS_BUILD_DIR -name '*.ino'); do
       echo
       echo
       echo -e '\033[0;36m'Building $SKETCH '\033[0m'
       echo
       arduino --verify $SKETCH || NFAIL=$((NFAIL+1))
     done
     [[ $NFAIL -eq 0 ]]
